export const appPaths = {
  app: '/app',
  account: '/app/user/account',
  home: '/',
  login: '/login',
  profile: '/app/profile',
  publicPolicies: '/app/politicas-publicas',
  publicPolicyCreate: '/app/politicas-publicas/new',
  publicPolicyDetail: '/app/politicas-publicas/$policyId',
  publicPolicyEdit: '/app/politicas-publicas/$policyId/edit',
  reportCreate: '/app/reports/new',
  reportDetail: '/app/reports/$reportId',
  reports: '/app/reports',
  register: '/register',
  user: '/app/user',
} as const
